### ISSUE TITLE
Update the web logo

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web-en#11]
At the moment, the web still uses the Czech logotype in the header. It needs to be switched for an English one from the [Brand repository](https://github.com/faktaoklimatu/graphics/tree/main/Brand).

However, we don't yet have the necessary versions generated which is blocking this issue. We'll update here once this is done.

**Comment by mgrabovsky** [comment]
I don't think missing input is the problem – you introduced the English version in 38d8d2, I replaced it in d060a3. IIRC, this is intentional – the brand is _Fakta o klimatu_ not _Facts on Climate_. @katkolouchova I think we discussed this briefly at some point when preparing the website. Do you remember the details?

**Comment by mukrop** [comment]
I did not know you discussed that. Although I find it a strange decision, I don't think reopening it is worth the case. @katkolouchova, can you confirm Matej's comment that the Czech logotype is intentional on the English website?

**Comment by katkolouch** [comment]
@mukrop Yes, we indeed decided to brand ourselves as Fakta o klimatu even in the English context. For example, it made sense when our graphics appeared in the ISFC conference in Prague held in English, but many of the guests were actually Czech. And I feel like that the English graphics are currently mostly used in Czechia for English speaking public.

We may revise this decision once we are actually present in an international context more often.

**Comment by mukrop** [comment]
Thanks for the explanation, closing for now.
If we get started to be used abroad more widely, I'll re-open this matter.
