### ISSUE TITLE
Pilot adding English explanatory texts

### ISSUE THREAD

**Issue by mukrop** [faktaoklimatu/web-en#9]
Currently, no English infographics have explanatory texts (insufficient capacity in the team). This issue is to track progress on getting some translations up.

I suggest starting with the Climate change scheme [[English page](https://factsonclimate.org/infographics/climate-change-scheme), [Czech page](https://faktaoklimatu.cz/infografiky/schema-klimaticke-zmeny)]. To get the explanatory text up, it is needed:
* Automatically bulk-translate the Czech text to English ([DeepL](https://www.deepl.com/translator) should work well, [Google Translate](https://translate.google.com/) is also worth a try).
* Proofread the English text and correct it to sound natural (sometimes, reformulating the sentence may be necessary). Let's not spend too much time here – it does not have to be the most elegant style ever but we aim for representative enough English.
* Create a pull request in [web-en GitHub repository](https://github.com/faktaoklimatu/web-en) adding in the text. (Assign @mukrop for review, please.)

General tips and tricks:
* The In theory, this can be done without the local build of the project website (just by adding the content in the web-en repo).
* Nevertheless, for the IT-skilled, a local build is preferred to check the generated output. Instructions are available in the [web-core](https://github.com/faktaoklimatu/web-core) repository that contains the main web engine.
* So far, there has not been many non-Czech speaking volunteers. Thus, there may be residues of Czech-only information. If this is in a place critical for understanding, contact @mukrop to correct this.

**Comment by willemfrishert** [comment]
@mukrop I tried to assign the PR to you but I don't think I have the required permissions. Maybe I could ask you to have a look and assign it to yourself?

**Comment by willemfrishert** [comment]
@mukrop I just updated the PR and was trying to assign this ticket back to you for review but accidentally pressed the "unassigned to me"-link.

Let me provide feedback on the PR so you can review it once more to see if these were the changes you were hoping to see.

**Comment by mukrop** [comment]
Closing as done. For an overview of missing accompanying texts, see #14.
